#!/usr/bin/env zsh

setopt no_nomatch

for file in "$@"; do
  if [[ ! -f "$file" ]]; then
    continue
  fi

  if [[ ! -f "${file}.zwc" || "$file" -nt "${file}.zwc" ]]; then
    zcompile "$file" >/dev/null 2>&1 || true
  fi
done