#!/bin/bash
# jira

git_jira() {
    # Check if the current directory is a Git repository
    if ! git rev-parse --is-inside-work-tree &>/dev/null; then
        echo "Error: Not in a valid Git repository. Please switch to a valid Git repository."
        return 1
    fi

    # Get the current ticket number using 'xgit ticket_code'
    ticket_number=$(git_ticket)

    # Check if 'xgit ticket_code' command failed (non-zero return code)
    if [[ $? -ne 0 ]]; then
        echo "Error: Could not retrieve the ticket number."
        return 1
    fi

    # Construct the Jira URL
    jira_url="https://ccvgroup.atlassian.net/browse/$ticket_number"

    # Use the 'b' command to open the URL
    b "$jira_url"
}
