#!/bin/bash
# history

function git_branchhistory() {
  branches=$(git reflog | grep "checkout" | awk '{print $NF}' | awk '!seen[$0]++' | head -n 10)
  if [ -z "$1" ]; then
    index=1
    echo "$branches" | while read branch; do
      echo "$index: $branch"
      index=$((index + 1))
    done
  else
    branch=$(echo "$branches" | sed -n "${1}p")
    if [ -n "$branch" ]; then
      git checkout "$branch"
      echo "Switched to branch '$branch'"
    else
      echo "Invalid index"
    fi
  fi
}
