#!/bin/bash

tbr() {
  # Loop through each file in the directory
  find "$TBDIR" \
    -type d \( -name "bin" -o -name ".*" \) -prune -o \
    -type f -print | while IFS= read -r file; do
    # Extract the basename
    filename="${file##*/}"

    # Skip if:
    # - Not a file
    # - Has a dot anywhere in the name
    # - Starts with a dot
    if [ ! -f "$file" ] || [[ "$filename" == *.* ]] || [[ "$filename" == .* ]]; then
      continue
    fi

    source "$file"
  done
}