#!/bin/bash

toolbox_initialize() {
  local bin_dir="$HOME/bin"

  mkdir -p "$bin_dir"

  # Add ~/bin to PATH if it's not already there
  if [[ ":$PATH:" != *":$bin_dir:"* ]]; then
    export PATH="$HOME/bin:$PATH"
  fi
}