#!/bin/bash

xgit() {
    # Directory containing the command files (directory of this script)
    COMMAND_DIR=$(dirname $functions_source[xgit])

    # Get all available aliases
    if [ -z "$1" ]; then
        grep -h '^#' "$COMMAND_DIR"/git_* | awk '/^# / {print $2}'
        return 0
    fi

    # Get the alias from the first argument and shift to remaining arguments
    alias="$1"; shift

    # Find and execute the corresponding command file if it exists
    command_file=$(grep -l "^# $alias" "$COMMAND_DIR"/git_* | grep -v "$COMMAND_DIR/xgit")

    if [ -n "$command_file" ]; then
        "$(basename "$command_file")" "$@"
    else
        echo "Alias '$alias' not found."
        return 1
    fi
}

# _xgit_autocomplete() {
#     local cur aliases
#     cur="${words[CURRENT]}"

#     # Capture the output of xgit and split it by newline
#     aliases=("${(@f)$(xgit)}")

#     # Remove the first element from the aliases array
#     aliases=("${aliases[@]:0}")

#     # Add the remaining aliases as autocomplete suggestions
#     compadd -X 'Available commands:' -l -- $aliases
# }

# compdef _xgit_autocomplete xgit