#!/bin/bash

toolbox_initialize() {
  # Setup bin dir
  local bin_dir="$TBDIR/bin"

  mkdir -p "$bin_dir"

  # Add ~/bin to PATH if it's not already there
  if [[ ":$PATH:" != *":$bin_dir:"* ]]; then
    export PATH="$bin_dir:$PATH"
  fi
}