#!/bin/bash

c_print_repo_map() {
    local color_reserved_label=""
    local color_reserved_keyword=""
    local color_reset=""

    if [[ -t 1 ]]; then
        color_reserved_label=$'\033[0;90m'
        color_reserved_keyword=$'\033[1;33m'
        color_reset=$'\033[0m'
    fi

    printf '%breserved:%b %b[local]%b %b[repos]%b\n' \
        "$color_reserved_label" "$color_reset" \
        "$color_reserved_keyword" "$color_reset" \
        "$color_reserved_keyword" "$color_reset"

    c_print_repo_map_rows "$(c_read_repo_map_cache)"
}