#!/bin/bash

c_find_and_cd() {
    local open_in_code="$1"
    local open_in_vs="$2"
    local query="$3"
    local preferred_index="$4"
    local results

    if [[ -z "$query" ]]; then
        echo "Usage: c [-c|-v] <query> [preferred-index]"
        return 1
    fi

    results="$(c_filter_by_abbreviation "$query")"

    if [[ -z "$results" ]]; then
        results="$(c_filter_by_abbreviation_text "$query")"
    fi

    if [[ -z "$results" ]]; then
        results="$(c_filter_by_folder_text "$query")"
    fi

    c_choose_and_cd "$results" "$preferred_index" "$open_in_code" "$open_in_vs"
}