#!/bin/bash

there_get_executable_name() {
    local resolved_path="$1"
    local executable_name

    executable_name="${resolved_path##*/}"
    executable_name="${executable_name##*\\}"
    executable_name="${executable_name%$'\r'}"
    printf '%s\n' "${executable_name%.*}"
}